### ISSUE TITLE
Link to Jim Cooke's presentation on Micron's website is not available

### ISSUE THREAD

**Issue by modal** [Cushychicken/cushychicken.github.io#1]
The link to Jim Cooke's presentation on Micron's website is not available.

http://www.dslreports.com/r0/download/1507743~59e7b9dda2c0e0a0f7ff119a7611c641/flash_mem_summit_jcooke_inconvenient_truths_nand.pdf

http://read.pudn.com/downloads151/ebook/654253/flash_mem_summit_jcooke_inconvenient_truths_nand.pdf

**Comment by Cushychicken** [comment]
I couldn't find a copy on the web, but I was able to dig up one I had saved on my home machine and upload to the page. Seems to be working just fine now, so let me know if you're still having issues!
